// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IFaSolidDraftingCompass: typeof import('~icons/fa-solid/drafting-compass')['default']
    IIconParkSolidWritingFluently: typeof import('~icons/icon-park-solid/writing-fluently')['default']
    IMaterialSymbolsArrowBack: typeof import('~icons/material-symbols/arrow-back')['default']
    IPhPersonSimpleRunBold: typeof import('~icons/ph/person-simple-run-bold')['default']
    LayoutWrapper: typeof import('./../src/components/includes/LayoutWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
